name:                lets-really-lens
version:             0.1.0.0
github:              "ford-prefect/lets-really-lens"
license:             BSD3
author:              "Arun Raghavan"
maintainer:          "arun@arunraghavan.net"
copyright:           "2019 Arun Raghavan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ford-prefect/lets-really-lens#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- lens-tutorial

library:
  source-dirs: src

executables:
  lets-really-lens-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lets-really-lens

tests:
  lets-really-lens-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lets-really-lens
